# Generated by Django 6.0.4 on 2026-05-03 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_cart_cartitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'ordering': ['user'], 'verbose_name': 'Корзина', 'verbose_name_plural': 'Корзины'},
        ),
    ]
